#阿里云秘钥
ACCESS_KEY_ID: LTAIGHgnWr0AAzvq
ACCESS_KEY_SECRET: VCBlyvwFeO6pYqgdwqLjwXjPz2dPco

#阿里云角色
ROLE_ARN: acs:ram::1008328175702202:role/abyss

#oss配置
BUCKET_NAME: the-wings-gaming
ROLE_SESSION_NAME: hjjsb
IMG_URL: IMG_URL
REGION: REGION
FILE: FILE
OSS_ENDPOINT: oss-cn-beijing.aliyuncs.com

#sts配置
STS_ENDPOINT: sts.cn-beijing.aliyuncs.com

#短信
SING_NAME: YOUR_SING_NAME
TEMPLATE_CODE: TEMPLATE_CODE
PRODUCT: Dysmsapi
DOMAIN: dysmsapi.aliyuncs.com
OSS_URL: https://the-wings-gaming.oss-cn-beijing.aliyuncs.com/

#身份证api
ID_CARD_API_HOST: https://idenauthen.market.alicloudapi.com
ID_CARD_API_PATH: /idenAuthentication
ID_CARD_API_CODE: 41f459974cde4e28849fc2a10d729ee1


